### ISSUE TITLE
release TODO

### ISSUE THREAD

**Issue by lachie** [flood-io/element#6]
- [ ] `time_to_first_interactive` polyfill not working
- [ ] uplift recast `No parser and no filepath given, using 'babylon' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred.`
- [ ] separate grid & cli

**Comment by ivanvanderbyl** [comment]
I think we can delay implementing the TTFI polyfil until after new Flood explorer epic is delivered.

**Comment by ivanvanderbyl** [comment]
Can't wait to announce this in Vienna. I owe you a 🍺 or 🍻
